---
title: "FA Assignment 9"
author: "Yunshuang Jiang"
date: "3/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Fit decomposition model to hft2 trades train.csv
```{r}
#Create the components of decomposition A, D and S.
hft <- read.csv("~/Desktop/assignments_Fonancial Analytics (32001)_Lecture 9_hft2_trades_train.csv")
hft$diff = c(NA, diff(hft$price))
hft = hft[-1,]
idx=c(1:19493)[hft$diff > 0]
jdx=c(1:19493)[hft$diff < 0]
A=rep(0,19493); A[idx]=1; A[jdx]=1
D=rep(0,19493); D[idx]=1; D[jdx]=-1

size <- rep(0,19493); 
size[hft$diff == -125]=1;size[hft$diff == -100]=2;size[hft$diff == -75]=3;
size[hft$diff == -50]=4;size[hft$diff == -25]=5;size[hft$diff == 0]=6;
size[hft$diff == 25]=7;size[hft$diff == 50]=8;size[hft$diff == 75]=9;
size[hft$diff == 100]=10;size[hft$diff == 125]=11;size[hft$diff == 150]=12;
size[hft$diff == 175]=13;size[hft$diff == 200]=14;size[hft$diff == 225]=15;
size[hft$diff == 250]=16;size[hft$diff == 175]=17;
S=abs(size-6)


#Create lagged variables
Ai=A[2:19493]; Aim1=A[1:19492]
Di=D[2:19493]; Dim1=D[1:19492]
Si=S[2:19493]; Sim1=S[1:19492]

#fit models 
m1=glm(Ai~Aim1,family="binomial")
summary(m1)


di=Di[Ai==1]
dim1=Dim1[Ai==1]
di=(di+abs(di))/2 # transform di to binary
m2=glm(di~dim1,family="binomial")
summary(m2)


si=Si[Di==1]
sim1=Sim1[Di==1]
datapath <- "/Users/berryjiang/Desktop"
source(paste(datapath,"GeoSize.R",sep="/"))
m3=GeoSize(si,sim1)


nsi=Si[Di==-1]
nsim1=Sim1[Di==-1]
m4=GeoSize(nsi,nsim1)


#extract parameters:
(beta_0 <- unname(m1$coefficients[1]))
(beta_1 <- unname(m1$coefficients[2]))
#plogis(beta_0)             # prob of Ai = 1 when Aim1 = 0
#plogis(beta_0 + 1*beta_1)  # prob of Ai = 1 when Aim1 = 1


(gamma_0 <- unname(m2$coefficients[1]))
(gamma_1 <- unname(m2$coefficients[2]))
#plogis(gamma_0 - 1*gamma_1)  # prob of Di = 1 when Ai = 1, Dim1 = -1
#plogis(gamma_0)              # prob of Di = 1 when Ai = 1, Dim1 =  0
#plogis(gamma_0 + 1*gamma_1)  # prob of Di = 1 when Ai = 1, Dim1 = +1

(theta_u0 <- unname(m3$par[1]))  #0.9222531
(theta_u1 <- unname(m3$par[2]))  #1.320356

(theta_d0 <- unname(m4$par[1]))  #0.9128689
(theta_d1 <- unname(m4$par[2]))   #1.189238


#function
# Pr( next_pch <= x | aim1, dim1, sim1 )
pch_decomposition_cdf <- function(x, aim1, dim1, sim1, decomp_params) {  
    pch_cdf <- 0
    p <- plogis(decomp_params$beta_0 + decomp_params$beta_1 * aim1)    # Pr( Ai =  1 | aim1 )
    q <- plogis(decomp_params$gamma_0 + decomp_params$gamma_1 * dim1)  # Pr( Di = +1 | dim1 )
    
    lambda_up = plogis(decomp_params$theta_u0 + decomp_params$theta_u1 * sim1)
    lambda_down = plogis(decomp_params$theta_d0 + decomp_params$theta_d1 * sim1)
    
    if (x < 0) {
        # P( next_pch <= x ) = Pr( Ai = 1, Di = -1, Si >= -x ) = Pr( Ai = 1, Di = -1, Si > -x-1 ) 
        # since Si ~ 1 + geom(lambda_down) when Di = -1 we have:
        pch_cdf <- p * (1-q) * pgeom(-x-2, prob=lambda_down, lower.tail = FALSE) 
    } else if (x >= 0) {
        # P( next_pch <= x ) = Pr( Ai = 0 ) + Pr( Ai = 1, Di = 1 ) + Pr( Ai = 1, Di = -1, Si <= x ) = 
        # = (1-p) + p*(1-q) + Pr( Ai = 1, Di = 1, Si <= x ) 
        # since Si ~ 1 + geom(lambda_up) when Di = 1 we have:
        pch_cdf <- (1-p) + p * (1-q) + p * q * pgeom(x-1, prob=lambda_up)
    }
    
    return(pch_cdf)
}

decomp_params <- list(beta_0 = beta_0, beta_1 = beta_1,
                      gamma_0 = gamma_0, gamma_1 = gamma_1,
                      theta_u0 = theta_u0, theta_u1 = theta_u1,
                      theta_d0 = theta_d0, theta_d1 = theta_d1)


#What is probability that price change of the next trade will be category -1 tick if current price change is not zero (A=1), negative (D=−1), and changed by 2 ticks?
(decomp_cross_prob <- pch_decomposition_cdf(-1, aim1=1, dim1=-1, sim1=2, decomp_params))
```
